
security:
  oauth2:
    client:
      access-token-uri: http://localhost:9999/sso-server/oauth/token
      user-authorization-uri: http://localhost:9999/sso-server/oauth/authorize
      clientId: client1
      clientSecret: clientSecret
    resource:
      user-info-uri: http://localhost:9999/sso-server/user
      prefer-token-info: false
zuul:
  routes:
    sso-server:
      path: /sso-server/**
      sensitiveHeaders:
      serviceId: oauth2-server
    client1:
      path: /client1/**
      sensitiveHeaders:
      serviceId: client1
    client2:
      path: /client2/**
      sensitiveHeaders:
      serviceId: client2
  add-proxy-headers: true
server:
  port: 8760
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystirx:
    enable: true
spring:
  application:
    name: api-gateway
