
security:
  oauth2:
    client:
      access-token-uri: http://localhost:8700/uaa/oauth/token
      user-authorization-uri: http://localhost:8700/uaa/oauth/authorize
      client-id: webapp
    resource:
      user-info-uri: http://localhost:8700/uaa/user
      prefer-token-info: false
zuul:
  routes:
    uaa:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: auth-server
    order:
      path: /order/**
      sensitiveHeaders:
      serviceId: order-service
  add-proxy-headers: true
server:
  port: 8764
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystirx:
    enable: true
spring:
  application:
    name: api-gateway
