server:
  port: 9999
#  servlet:
#    context-path: /oauth2-server

# 这里的name不能加"/" 否则在注册服务时，会使用 "localhost:/OAUTH2_SERVER:9999/oauth2_server" 来注册
spring:
  application:
    name: oauth2-server
  # MySQL 数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/oauth?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: koral
    password: password
  # 更新创建表
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hbm2ddl:
          auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true