security:
  oauth2:
    client:
      clientId: client1
      clientSecret: clientSecret
      user-authorization-uri: http://localhost:9999/server/oauth/authorize
      access-token-uri: http://localhost:9999/server/oauth/token
    resource:
      jwt:
        key-uri: http://localhost:9999/server/oauth/token_key

server:
  port: 8080
  servlet:
    #    context-path 必须带上"/"
    context-path: /client1