# 服务名
spring:
  application:
    name: client1
  datasource:
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth?characterEncoding=UTF-8
# 指定认证服务器配置
security:
  oauth2:
    client:
      clientId: ${spring.application.name}
      clientSecret: clientSecret
      user-authorization-uri: http://localhost:9999/oauth2-server/oauth/authorize
      access-token-uri: http://localhost:9999/oauth2-server/oauth/token
    resource:
      jwt:
        key-uri: http://localhost:9999/oauth2-server/oauth/token_key

# 声明端口与前缀
server:
  port: 8080
  servlet:
    #    context-path 必须带上"/"
    context-path: /${spring.application.name}

# 注册Eureka服务
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
