security:
  oauth2:
    client:
      clientId: client2
      #      Basic Y2xpZW50MTpjbGllbnRTZWNyZXQ=
      clientSecret: clientSecret
      user-authorization-uri: http://localhost:9999/server/oauth/authorize
      access-token-uri: http://localhost:9999/server/oauth/token
      registered-redirect-uri: http://localhost:${server.port}/${security.oauth2.client.clientId}/index.html
    resource:
      jwt:
        key-uri: http://localhost:9999/server/oauth/token_key

server:
  port: 8060
  servlet:
    #    context-path 必须带上"/"
    context-path: /client2