security:
  oauth2:
    client:
      clientId: client2
      #      Basic Y2xpZW50MTpjbGllbnRTZWNyZXQ=
      clientSecret: clientSecret
      user-authorization-uri: http://127.0.0.1:9999/server/oauth/authorize
      access-token-uri: http://127.0.0.1:9999/server/oauth/token
    resource:
      jwt:
        key-uri: http://127.0.0.1:9999/server/oauth/token_key


server:
  port: 8060
  servlet:
    #    context-path 必须带上"/"
    context-path: /client2