server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.cloud.*: debug

spring:
  application:
    name: biz-server

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: cloud-user

security:
  oauth2:
    client:
      client-id: hq
      client-secret: hq
      user-authorization-uri: http://localhost:8762/oauth/authorize
      grant-type: password
      scope: xx
      access-token-uri: http://localhost:8762/oauth/token
    resource:
      user-info-uri: http://localhost:8762/user
    authorization:
      check-token-access: http://localhost:8762/oauth/check_token

feign:
  hystrix:
    enabled: true